# This GitLab file is meant to be a test for the template repo itself.
# You should replace it with your own workflow file for your project.

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-linux:
  stage: build
  parallel:
    matrix:
      - COMPILER: [gcc-11, gcc-12, clang-11.0.1, clang-12, clang-13, clang-14]
  image: $CI_REGISTRY/idi/dockerfiles/cmake-cpp:$COMPILER
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && (($COMPILER =~ /(gcc-12|clang-13|clang-14)$/))
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" # Only on push events (same as 'except: merge_requests')
  script:
    - cmake --version
    - |
      echo "Test Compilers"
      if [[ $COMPILER =~ ^gcc ]]; then
        gcc --version && g++ --version
      elif [[ $COMPILER =~ ^clang ]]; then
        clang --version && clang++ --version
      fi
    - mkdir -p build && cd build && cmake .. -DIDI_USE_BUILD_TIMESTAMPS=1 -DIDI_BUILD_DEMOS=1 -DIDI_GIT_BRANCH_NAME="$CI_COMMIT_BRANCH" && cmake --build . -j 8
    - |
      if ! ctest -C Debug --output-junit ctest.xml ; then
        cat Testing/Temporary/LastTest.log && exit 1
      fi
  interruptible: true
  artifacts:
    paths:
      - build/bin/template_project
      - build/ctest.xml
    reports:
      junit: build/ctest.xml
