# This GitLab file is meant to be a test for the template repo itself.
# You should replace it with your own workflow file for your project.

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_ARGS: -DTEMPLATE_PROJECT_BUILD_DEMOS=1 -DTEMPLATE_PROJECT_BUILD_TESTS=1 -DTEMPLATE_PROJECT_USE_BUILD_TIMESTAMPS=1 -DTEMPLATE_PROJECT_DO_TEMPLATE_COMPONENT_TEST=1 -DTEMPLATE_PROJECT_CI_GIT_BRANCH_NAME="$CI_COMMIT_REF_NAME"

build-linux:
  stage: build
  parallel:
    matrix:
      #- COMPILER: [gcc-11, gcc-12, clang-11.0.1, clang-12, clang-13, clang-14]
      - COMPILER: [clang-14]
        TYPE: [exe, static, shared]
  variables:
    CONFIGS: '{ "exe": "platform_config.cmake", "static": "platform_config.static.cmake", "shared": "platform_config.shared.cmake" }'
  image: $CI_REGISTRY/idi/dockerfiles/cmake-cpp:$COMPILER
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && (($COMPILER =~ /(gcc-12|clang-13|clang-14)$/))
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" # Only on push events (same as 'except: merge_requests')
  before_script:
    - apt-get install -y -qq jq
  script:
    - cmake --version
    - |
      echo "Test Compilers"
      if [[ $COMPILER =~ ^gcc ]]; then
        gcc --version && g++ --version
      elif [[ $COMPILER =~ ^clang ]]; then
        clang --version && clang++ --version
      fi
    - mkdir -p build && cd build
    - cmake .. $CMAKE_ARGS -DIDI_PLATFORM_CONFIG=../$(echo $CONFIGS | jq -r .$TYPE)
    - cmake --build . -j 8
    - ctest -C Debug --output-junit ctest.xml
  interruptible: true
  artifacts:
    when: always
    paths:
      - build/ctest.xml
    reports:
      junit: build/ctest.xml
