# This GitLab file is meant to be a test for the template repo itself.
# You should replace it with your own workflow file for your project.

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

.linux-builds:
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ubuntu:21.04
        COMPILER: gcc
        VERSION: 10
      - IMAGE: ubuntu:21.04
        COMPILER: gcc
        VERSION: 11
      - IMAGE: ubuntu:21.04
        COMPILER: clang
        VERSION: 11
      - IMAGE: ubuntu:21.04
        COMPILER: clang
        VERSION: 12
      - IMAGE: ubuntu:21.10
        COMPILER: clang
        VERSION: 13

  rules:
    # Only on push events (same as 'only: [branches, tags]')
    - if: $CI_PIPELINE_SOURCE == "push" && "$COMPILER-$VERSION" =~ /^(gcc-(11)|clang-(12|13))$/
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "push"
      allow_failure: false

build-linux:
  stage: build
  extends: .linux-builds
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake
    - |
      echo "Install Tools"
      if [[ $COMPILER == gcc ]]; then
        apt-get install -y -qq gcc-$VERSION g++-$VERSION
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$VERSION 100
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-$VERSION 100
      elif [[ $COMPILER == clang ]]; then
        DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq clang-$VERSION
        update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$VERSION 100
        update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-$VERSION 100
      fi
  script:
    - cmake --version
    - |
      echo "Test Compilers"
      if [[ $COMPILER == gcc ]]; then
        gcc --version
        g++ --version
      elif [[ $COMPILER == clang ]]; then
        clang --version
        clang++ --version
      fi
    - mkdir -p build && cd build && cmake .. -DIDI_BUILD_DEMOS=1 && cmake --build . -j 8
    - |
      if ! ctest -C Debug ; then
        cat Testing/Temporary/LastTest.log
      fi
  interruptible: true
  artifacts:
    paths:
      - build/bin/template_project
