

macro(do_replace_dir)
    message(STATUS "\tFramework update - Updating ${ARGV0}")
    file(REMOVE_RECURSE "${CMAKE_CURRENT_SOURCE_DIR}/${ARGV0}")
    file(COPY "${FRAMEWORK_UPDATE_DIR}/${ARGV0}" DESTINATION "${CMAKE_CURRENT_SOURCE_DIR}/${ARGV0}")
    message(STATUS "\tFramework update - Done Updating ${ARGV0}")
endmacro()

macro(do_replace_file)
    message(STATUS "\tFramework update - Updating ${ARGV0}")
    file(REMOVE "${CMAKE_CURRENT_SOURCE_DIR}/${ARGV0}")
    file(COPY_FILE "${FRAMEWORK_UPDATE_DIR}/${ARGV0}" "${CMAKE_CURRENT_SOURCE_DIR}/${ARGV0}")
    message(STATUS "\tFramework update - Done Updating ${ARGV0}")
endmacro()

do_replace_dir("cmake/idi/")
do_replace_dir("src/base/")
set(IDICMAKE_PLATFORM_CONFIG "${CMAKE_CURRENT_SOURCE_DIR}/platform-config.cmake")
include("${IDICMAKE_PLATFORM_CONFIG}")
if(DEFINED IDI_PROJECT_NAME)
    message(WARNING "Attention! It appears that your project contains files using the old IDI_ prefix instead of the new IDICMAKE_ prefix in files such a platform-config.cmake and other .cmake files! Please update these manually or problems may occur!")
    set(IDICMAKE_PROJECT_NAME ${IDI_PROJECT_NAME})
endif()
file(RENAME "${CMAKE_CURRENT_SOURCE_DIR}/src/base/include/template_project" "${CMAKE_CURRENT_SOURCE_DIR}/src/base/include/${IDICMAKE_PROJECT_NAME}")
do_replace_file("CMakeLists.txt")
do_replace_file("src/CMakeLists.txt")
do_replace_file("lib/.gitignore")
