# This GitHub workflow file is meant to be a test for the template repo itself.
# You should replace it with your own workflow file for your project.

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        type: [exe, static, shared]
    env:
      CMAKE_ARGS: -DTEMPLATE_PROJECT_BUILD_DEMOS=1 -DTEMPLATE_PROJECT_BUILD_TESTS=1 -DTEMPLATE_PROJECT_USE_BUILD_TIMESTAMPS=1 -DTEMPLATE_PROJECT_DO_TEMPLATE_COMPONENT_TEST=1 -DTEMPLATE_PROJECT_CI_GIT_BRANCH_NAME="${{ github.ref_name }}"
      CONFIGS: '{ "exe": "platform_config.cmake", "static": "platform_config.static.cmake", "shared": "platform_config.shared.cmake" }'

    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create build directory
      run: mkdir -p build

    - name: Build
      shell: bash
      run: |
        export PATH=$HOME/cmake/bin:$PATH
        cmake --version
        cd build
        cmake .. $CMAKE_ARGS -DIDI_PLATFORM_CONFIG=../${{ fromJSON(env.CONFIGS)[matrix.type] }}
        cmake --build . -j 8
        ctest -C Debug --output-junit ctest.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: idi-cpp-template-${{ matrix.type }}-${{ matrix.os }}
        path: build/ctest.xml
